config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root 'homes#index'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
    resources :missions, except: [:show] do
      get :gantt, on: :member
      resources :projects, only: %i[index new create]
    end
    resources :projects, only: %i[edit update destroy] do
      resources :milestones, only: %i[index new create]
    end
    resources :milestones, only: %i[edit update destroy] do
      resources :requirements, only: %i[index new create]
    end
    resources :requirements, only: %i[edit update destroy] do
      resources :tickets, only: %i[index new create]
    end
    resources :tickets, only: %i[edit update destroy] do
      member do
        patch :update_doing
        patch :update_done
      end
    end
  end
end

app/models/milestone.rb
class Milestone < ApplicationRecord
  has_many :requirements, dependent: :destroy
  has_many :tickets, through: :requirements
  has_many :tickets_notyet, -> { where(tickets: { status: :notyet }) }, class_name: 'Ticket', through: :requirements
  has_many :tickets_doing, -> { where(tickets: { status: :doing }) }, class_name: 'Ticket', through: :requirements
  has_many :tickets_done, -> { where(tickets: { status: :done }) }, class_name: 'Ticket', through: :requirements

  belongs_to :project

  enum status: %i[notyet doing done]
  validates :name, presence: true, uniqueness: { scope: :project_id }, length: { maximum: 50 }
  validates :status, presence: true

  scope :includes_tickets_by_status, -> {
    includes(:tickets_notyet).includes(:tickets_doing).includes(:tickets_done)
  }

  def edit_path
    Rails.application.routes.url_helpers.edit_milestone_path(id:)
  end

  def breadcrumbs
    [
      *project.breadcrumbs,
      { name:, path: edit_path }
    ]
  end
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_milestone, only: %i[edit update destroy]
  before_action :fetch_requirements, only: [:edit]
  before_action :fetch_project, only: %i[new create]

  def new
    @milestone = @project.milestones.build
  end

  def edit; end

  def create
    @milestone = @project.milestones.build(milestone_params)
    if @milestone.save
      redirect_to edit_project_path(@project.id), notice: t('.succeeded')
    else
      flash[:alert] = t('.failed')
      render 'new'
    end
  end

  def update
    if @milestone.update(milestone_params)
      redirect_back fallback_location: edit_milestone_path(@milestone.id), notice: t('.succeeded')
    else
      flash[:alert] = t('.failed')
      render 'edit'
    end
  end

  def destroy
    if @milestone.destroy
      redirect_back fallback_location: missions_path, notice: t('.succeeded')
    else
      flash[:warning] = t('.failed')
    end
  end

  private

  def fetch_milestone
    @milestone = current_user.milestones.find(params[:id])
  end

  def fetch_requirements
    @requirements = current_user.requirements.where(milestone_id: params[:id]).includes_tickets_by_status.all
  end

  def fetch_project
    @project = current_user.projects.find(params[:project_id])
  end

  def milestone_params
    params.require(:milestone).permit(:name, :description, :due_date, :close_date, :status)
  end
end

app/views/milestones/_form.html.haml
= f.input :name
= f.input :description, as: :text
= f.input :due_date, as: :date, html5: true, input_html: { value: milestone.due_date || Date.today }
= f.input :closed_date, as: :date, html5: true, input_html: { value: milestone.closed_date }
= f.input :status, collection: Milestone.statuses_i18n, include_blank: false
= f.button :submit, class: 'btn-success'

app/views/milestones/_list.html.haml
%table.table
  %thead
    %tr
      %td
        = t('activerecord.attributes.milestone.name')
      %td
        = t('activerecord.attributes.milestone.due_date')
      %td
        = t('activerecord.attributes.milestone.status')
      %td
        = t('activerecord.attributes.milestone.ticket_count_by_status')
      %td
        = t('destroy')
  %tbody
    - milestones.each do |m|
      %tr
        %td
          = link_to m.name, edit_milestone_path(m.id),
            'data-bs-toggle' => 'tooltip', title: m.description
        %td
          = I18n.l(m.due_date)
        %td
          = m.status_i18n
        %td
          #{m.tickets_notyet.size} / #{m.tickets_doing.size} / #{m.tickets_done.size}
        %td
          = button_to t('destroy'), milestone_path(m.id), method: :delete, class: 'btn btn-danger btn-sm'

app/views/milestones/edit.html.haml
= render 'common/breadcrumb', { breadcrumbs: @milestone.breadcrumbs }
%h2
  = t('.')
= simple_form_for @milestone, url: milestone_path(@milestone.id) do |f|
  = render 'form', { f: f, milestone: @milestone }
%hr
%h3
  = t('requirements.index')
= button_to t('new'), new_milestone_requirement_path(@milestone.id), method: :get, class: 'btn btn-primary'
= render 'requirements/list', { requirements: @requirements }

app/views/milestones/new.html.haml
%h2
  = t('.')
= simple_form_for @milestone, url: project_milestones_path(@milestone.project.id) do |f|
  = render 'form', { f: f, milestone: @milestone }