config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root 'homes#index'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
    resources :missions, except: [:show] do
      get :gantt, on: :member
      resources :projects, only: %i[index new create]
    end
    resources :projects, only: %i[edit update destroy] do
      resources :milestones, only: %i[index new create]
    end
    resources :milestones, only: %i[edit update destroy] do
      resources :requirements, only: %i[index new create]
    end
    resources :requirements, only: %i[edit update destroy] do
      resources :tickets, only: %i[index new create]
    end
    resources :tickets, only: %i[edit update destroy] do
      member do
        patch :update_doing
        patch :update_done
      end
    end
  end
end

app/models/requirement.rb
class Requirement < ApplicationRecord
  has_many :tickets
  has_many :tickets_notyet, -> { where(status: :notyet) }, class_name: 'Ticket'
  has_many :tickets_doing, -> { where(status: :doing) }, class_name: 'Ticket'
  has_many :tickets_done, -> { where(status: :done) }, class_name: 'Ticket'
  belongs_to :milestone

  validates :name, presence: true, uniqueness: { scope: :milestone_id }, length: { maximum: 20 }
  validates :description, length: { maximum: 200 }

  scope :includes_tickets_by_status, -> {
    includes(:tickets_notyet).includes(:tickets_doing).includes(:tickets_done)
  }

  def edit_path
    Rails.application.routes.url_helpers.edit_requirement_path(id:)
  end

  def breadcrumbs
    [
      *milestone.breadcrumbs,
      { name:, path: edit_path }
    ]
  end
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_requirement, only: %i[edit update destroy]
  before_action :fetch_tickets, only: [:edit]
  before_action :fetch_milestone, only: %i[new create]

  def new
    @requirement = @milestone.requirements.build
  end

  def edit; end

  def create
    @requirement = @milestone.requirements.build(requirement_params)
    if @requirement.save
      redirect_to edit_milestone_path(@milestone.id), notice: t('.succeeded')
    else
      flash[:alert] = t('.failed')
      render 'new'
    end
  end

  def update
    if @requirement.update(requirement_params)
      redirect_back fallback_location: edit_requirement_path(@requirement.id), notice: t('.succeeded')
    else
      flash[:alert] = t('.failed')
      render 'edit'
    end
  end

  def destroy
    if @requirement.destroy
      redirect_back fallback_location: missions_path, notice: t('.succeeded')
    else
      flash[:warning] = t('.failed')
    end
  end

  private

  def fetch_requirement
    @requirement = current_user.requirements.find(params[:id])
  end

  def fetch_tickets
    @tickets = current_user.tickets.where(requirement_id: params[:id]).order_by_plan.all
  end

  def fetch_milestone
    @milestone = current_user.milestones.find(params[:milestone_id])
  end

  def requirement_params
    params.require(:requirement).permit(:name, :description)
  end
end

app/views/requirements/_form.html.haml
= f.input :name
= f.input :description, as: :text
= f.button :submit, class: 'btn-success'

app/views/requirements/_list.html.haml
%table.table
  %thead
    %tr
      %td
        = t('activerecord.attributes.requirement.name')
      %td
        = t('activerecord.attributes.requirement.description')
      %td
        = t('activerecord.attributes.requirement.ticket_count_by_status')
      %td
        = t('destroy')
  - requirements.each do |r|
    %tr
      %td
        = link_to r.name, edit_requirement_path(r.id)
      %td
        = r.description
      %td
        #{r.tickets_notyet.size} / #{r.tickets_doing.size} / #{r.tickets_done.size}
      %td
        = button_to t('destroy'), requirement_path(r.id), method: :delete, class: 'btn btn-danger btn-sm'

app/views/requirements/edit.html.haml
= render 'common/breadcrumb', { breadcrumbs: @requirement.breadcrumbs }
%h2
  = t('.')
= simple_form_for @requirement, url: requirement_path(@requirement.id) do |f|
  = render 'form', { f: f }
%hr
%h3
  = t('tickets.index')
= button_to t('new'), new_requirement_ticket_path(@requirement.id), method: :get, class: 'btn btn-primary'
= render 'tickets/list', { tickets: @tickets }

app/views/requirements/new.html.haml
%h2
  = t('.')
= simple_form_for @requirement, url: milestone_requirements_path(@requirement.milestone.id) do |f|
  = render 'form', { f: f }