config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root 'homes#index'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
    resources :missions, except: [:show] do
      get :gantt, on: :member
      resources :projects, only: %i[index new create]
    end
    resources :projects, only: %i[edit update destroy] do
      resources :milestones, only: %i[index new create]
    end
    resources :milestones, only: %i[edit update destroy] do
      resources :requirements, only: %i[index new create]
    end
    resources :requirements, only: %i[edit update destroy] do
      resources :tickets, only: %i[index new create]
    end
    resources :tickets, only: %i[edit update destroy] do
      member do
        patch :update_doing
        patch :update_done
      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_user_relationships, autosave: true, dependent: :destroy
  has_many :users, through: :project_user_relationships
  has_many :milestones, dependent: :destroy
  belongs_to :mission

  enum status: %i[notyet doing done]
  validates :name, presence: true, uniqueness: { scope: :mission_id }, length: { maximum: 20 }
  validates :description, length: { maximum: 200 }
  validates :status, presence: true

  def edit_path
    Rails.application.routes.url_helpers.edit_project_path(id:)
  end

  def breadcrumbs
    [
      *mission.breadcrumbs,
      { name:, path: edit_path }
    ]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_mission, only: %i[new create]
  before_action :fetch_project, only: %i[edit update destroy]
  before_action :fetch_milestones, only: [:edit]

  def new
    @project = @mission.projects.build
  end

  def edit; end

  def create
    @project = @mission.projects.build(project_params)
    @project.project_user_relationships.build(user: current_user, role: :owner)
    if @project.save
      redirect_to edit_mission_path(params[:mission_id]), notice: t('.succeeded')
    else
      flash[:alert] = t('.failed')
      render 'new'
    end
  end

  def update
    if @project.update(project_params)
      redirect_back fallback_location: edit_project_path(@project.id), notice: t('.succeeded')
    else
      flash[:alert] = t('.failed')
      render 'edit'
    end
  end

  def destroy
    if @project.destroy
      redirect_back fallback_location: missions_path, notice: t('.succeeded')
    else
      flash[:warning] = t('.failed')
    end
  end

  private

  def fetch_mission
    @mission = current_user.missions.find(params[:mission_id])
  end

  def fetch_project
    @project = current_user.projects.find(params[:id])
  end

  def fetch_milestones
    @milestones = current_user.milestones
                              .where(project_id: params[:id])
                              .includes_tickets_by_status
                              .order(:due_date).all
  end

  def project_params
    params.require(:project).permit(:name, :description, :status)
  end
end

app/views/projects/_form.html.haml
= f.input :name
= f.input :description, as: :text
= f.input :status, collection: Project.statuses_i18n, include_blank: false
= f.button :submit, class: 'btn-success'

app/views/projects/_list.html.haml
%table.table
  %thead
    %tr
      %td
        = t('activerecord.attributes.project.name')
      %td
        = t('activerecord.attributes.project.description')
      %td
        = t('activerecord.attributes.project.status')
      %td
        = t('destroy')
  - projects.each do |p|
    %tr
      %td
        = link_to p.name, edit_project_path(p.id)
      %td
        = p.description
      %td
        = p.status_i18n
      %td
        = button_to t('destroy'), project_path(p.id), method: :delete, class: 'btn btn-danger btn-sm'

app/views/projects/edit.html.haml
= render 'common/breadcrumb', { breadcrumbs: @project.breadcrumbs }
%h2
  = t('.')
= simple_form_for @project, url: project_path(@project.id) do |f|
  = render 'form', { f: f }
%hr
%h3
  = t('milestones.index')
= button_to t('new'), new_project_milestone_path(@project.id), method: :get, class: 'btn btn-primary'
= render 'milestones/list', { milestones: @milestones }

app/views/projects/new.html.haml
%h2
  = t('.')
= simple_form_for @project, url: mission_projects_path(@project.mission.id) do |f|
  = render 'form', { f: f }