config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root 'homes#index'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
    resources :missions, except: [:show] do
      get :gantt, on: :member
      resources :projects, only: %i[index new create]
    end
    resources :projects, only: %i[edit update destroy] do
      resources :milestones, only: %i[index new create]
    end
    resources :milestones, only: %i[edit update destroy] do
      resources :requirements, only: %i[index new create]
    end
    resources :requirements, only: %i[edit update destroy] do
      resources :tickets, only: %i[index new create]
    end
    resources :tickets, only: %i[edit update destroy] do
      member do
        patch :update_doing
        patch :update_done
      end
    end
  end
end

app/models/mission.rb
class Mission < ApplicationRecord
  has_many :mission_user_relationships, autosave: true, dependent: :destroy
  has_many :users, through: :mission_user_relationships
  has_many :projects, dependent: :destroy
  has_many :milestones, through: :projects
  has_many :requirements, through: :milestones
  has_many :tickets, through: :requirements

  enum status: %i[notyet doing done]
  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :description, length: { maximum: 200 }
  validates :status, presence: true

  def edit_path
    Rails.application.routes.url_helpers.edit_mission_path(id:)
  end

  def breadcrumbs
    [{ name:, path: edit_path }]
  end

  def jsonify_all
    as_json(
      include: { projects: {
        include: { milestones: {
          include: { requirements: {
            include: [:tickets]
          } }
        } }
      } }
    )
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_mission, only: %i[edit update destroy]
  before_action :fetch_all_of_mission, only: %i[gantt]

  def index
    @missions = current_user.missions.all
  end

  def new
    @mission = current_user.missions.build
  end

  def edit; end

  def create
    @mission = current_user.missions.build(mission_params)
    @mission.mission_user_relationships.build(user: current_user, role: :owner)
    if @mission.save
      redirect_to missions_path, notice: t('.succeeded')
    else
      flash[:alert] = t('.failed')
      render 'new'
    end
  end

  def update
    if @mission.update(mission_params)
      redirect_to edit_mission_path, notice: t('.succeeded')
    else
      flash[:alert] = t('.failed')
      render 'edit'
    end
  end

  def destroy
    if @mission.destroy
      redirect_back fallback_location: missions_path, notice: t('.succeeded')
    else
      flash[:warning] = t('.failed')
    end
  end

  def gantt; end

  private

  def fetch_mission
    @mission = current_user.missions.eager_load(:projects).find(params[:id])
  end

  def mission_params
    params.require(:mission).permit(:name, :description, :status)
  end

  def fetch_all_of_mission
    @mission = current_user.missions
                           .eager_load(:projects)
                           .eager_load(projects: :milestones)
                           .eager_load(milestones: :requirements)
                           .eager_load(requirements: :tickets)
                           .find(params[:id])
  end
end

app/views/missions/_form.html.haml
= simple_form_for mission do |f|
  = f.input :name
  = f.input :description, as: :text
  = f.input :status, collection: Mission.statuses_i18n, include_blank: false
  = f.button :submit, class: 'btn-success'

app/views/missions/_list.html.haml
%table.table
  %thead
    %tr
      %td
        = t('activerecord.attributes.mission.name')
      %td
        = t('activerecord.attributes.mission.description')
      %td
        = t('activerecord.attributes.mission.status')
      %td
        = t('destroy')
  %tbody
    - missions.each do |m|
      %tr
        %td
          = link_to m.name, edit_mission_path(m.id)
        %td
          = m.description
        %td
          = m.status_i18n
        %td
          = button_to t('destroy'), mission_path(m.id), method: :delete, class: 'btn btn-danger btn-sm'

app/views/missions/edit.html.haml
= render 'common/breadcrumb', { breadcrumbs: @mission.breadcrumbs }
%h2
  = t('.')
= render 'form', { mission: @mission }
%hr
%h3
  = t('projects.index')
= button_to t('new'), new_mission_project_path(@mission.id), method: :get, class: 'btn btn-primary'
= render 'projects/list', { projects: @mission.projects }

app/views/missions/gantt.html.haml
%h2
  = t('gantt')
= react_component('GanttOutline', { mission: @mission.jsonify_all })

app/views/missions/index.html.haml
%h2
  = t('.')
= button_to t('new'), new_mission_path, method: :get, class: 'btn btn-primary'
= render 'list', { missions: @missions }

app/views/missions/new.html.haml
%h2
  = t('.')
= render 'form', { mission: @mission }